In [1]:
import numpy as np

Creating a one dimensional Array

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

Creating Two dimensional Array

In [4]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

creating an array of zeros

In [5]:
np.zeros(3)

array([0., 0., 0.])

Creating a multidimensional array of zeros

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

creating an array of ones

In [8]:
np.ones(3)

array([1., 1., 1.])

creating a multidimensional array of ones

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

creating an identity matrix

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Creating an array of equally divided number

In [14]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

creating an array of numbers between certain range

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

creating an array of particular number

In [17]:
np.full((2, 3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

creating an array of particular size where number ranging between 0 and 1

In [18]:
np.random.rand(4, 5)

array([[0.20155766, 0.67379699, 0.64772002, 0.53528805, 0.253774  ],
       [0.31507667, 0.41005087, 0.13872916, 0.77251234, 0.32398084],
       [0.34676047, 0.48011423, 0.7421441 , 0.51260952, 0.37056913],
       [0.22770244, 0.02479975, 0.06222817, 0.21882574, 0.06774162]])

creating an array of particular size where number ranging from 0 to 100

In [19]:
np.random.rand(4, 5) * 100

array([[20.58575155, 49.39112761, 69.79871959, 82.01558866, 14.85052184],
       [87.9561033 , 91.53741271, 80.47581145, 34.71181367, 96.34225263],
       [21.09455177, 47.24964666, 67.9706803 , 52.22270213, 41.48197304],
       [35.36921538, 75.1375274 , 31.72136925, 24.34869616, 11.600795  ]])

generating a random number from 0 to particular number

In [23]:
np.random.randint(10)

2

generating a random number in an array

In [25]:
k = np.random.randint(10, size=(2,3))
k

array([[0, 1, 8],
       [1, 3, 2]])

finding the size of the array

In [26]:
k.size

6

finding the shape of the array

In [27]:
k.shape

(2, 3)

checking the data type of the array

In [28]:
k.dtype

dtype('int64')

converting array into particular data type

In [30]:
k.astype('int32')

array([[0, 1, 8],
       [1, 3, 2]], dtype=int32)

converting array into list

In [31]:
k.tolist()

[[0, 1, 8], [1, 3, 2]]

to check the info of any keyword

In [32]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [35]:
np.info(k.tolist())

Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


creating a new array from existing array

In [36]:
newk = np.copy(k)

In [37]:
newk

array([[0, 1, 8],
       [1, 3, 2]])

In [38]:
newk.sort()

In [39]:
newk

array([[0, 1, 8],
       [1, 2, 3]])

converting a 2D array into 1D array

In [43]:
newk.flatten()

array([0, 1, 8, 1, 2, 3])

finding transpose of an array

In [46]:
newk.T

array([[0, 1],
       [1, 2],
       [8, 3]])

Reshaping an array

In [59]:
newk.reshape(3,2)

array([[0, 1],
       [8, 1],
       [2, 3]])

In [60]:
newk

array([[0, 1, 8],
       [1, 2, 3]])

appending new array in the existing one

In [81]:
np.append(newk, [[5, 6, 7]])

array([0, 1, 8, 1, 2, 3, 5, 6, 7])

In [82]:
newwk = np.array([2, 3, 4])

In [89]:
newk[1,2]

3

In [90]:
newk[newk<8]

array([0, 1, 1, 2, 3])

to calculate mean of the array

In [91]:
np.mean(newk)

2.5

to calculate sum of the array

In [92]:
np.sum(newk)

15

to calculate minimum of array

In [93]:
np.min(newk)

0

to calculate maximum of the array

In [94]:
np.max(newk)

8

to calculate variance of the array

In [95]:
np.var(newk)

6.916666666666667

to calculate the standard deviation of the array

In [96]:
np.std(newk)

2.6299556396765835